### ISSUE TITLE
🚀 Rocket Positioning

### ISSUE THREAD

**Issue by gvee-uk** [gvee-uk/py-jump#25]
Shh, don't tell everyone, but you can actually jump over the highest rockets.

Should a 4th, higher rocket be introduced to mean that you _have_ to duck at some points?

The code change is easy enough: extend the `FLYER_HEIGHTS` list in `constants.py`.

**Comment by PsypherPunk** [comment]
Haven't looked at the code but does it need to be predetermined? Could it be randomly generated between, say, duck height and peak-of-jump height?

**Comment by gvee-uk** [comment]
It could definitely be calculated, but I was lazy on my first implementation, so... 🤷
